export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SAVE_PROFILE = 'SAVE_PROFILE';
export const SAVE_PROFILE_IMAGE = 'SAVE_PROFILE_IMAGE';
export const GET_CURRENT_GEOLOCATION = 'GET_CURRENT_GEOLOCATION';


