export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SAVE_PROFILE = 'SAVE_PROFILE';
export const SAVE_PROFILE_IMAGE = 'SAVE_PROFILE_IMAGE';
export const GET_CURRENT_GEOLOCATION = 'GET_CURRENT_GEOLOCATION';
export const GET_CLOSEST_USERS = 'GET_CLOSEST_USERS';
export const SELECT_COMMON_INTERESTS = 'SELECT_COMMON_INTERESTS';


