export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SAVE_PROFILE = 'SAVE_PROFILE';
export const SAVE_PROFILE_IMAGE = 'SAVE_PROFILE_IMAGE';
export const SAVE_CURRENT_GEOLOCATION = 'SAVE_CURRENT_GEOLOCATION';
export const SAVE_CLOSEST_USERS = 'SAVE_CLOSEST_USERS';
export const SELECT_COMMON_INTERESTS = 'SELECT_COMMON_INTERESTS';
export const UNSELECT_COMMON_INTERESTS = 'UNSELECT_COMMON_INTERESTS';
export const ADD_USER_INTERESTS = 'ADD_USER_INTERESTS';
export const REMOVE_USER_INTERESTS = 'REMOVE_USER_INTERESTS';



